version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
